// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class MenuButtonScript : MonoBehaviour
{

	public Vector3 menuSelectOffset = new Vector3(0,0,0);
	public Vector3 menuSelectScale = new Vector3(1,1,1);


	public string buttonName = "noname";

	public int playerNumber = 0; //0 for all, 1 for p1, 2 for p2, etc


	void Start(){	
//		this.renderer.material.color = Color.green;
//		SetSelected(false);
	}

	void OnMouseEnter(){
		SetSelected(true);
		MainMenu.instance.SetSelectedButton(gameObject);
		MainMenu.instance.SetMenuSelectorMouse();
	}

	void OnMouseExit() {
		SetSelected(false);
//		if(MainMenu.instance.menuSelect.activeSelf)
			MainMenu.instance.SetMenuSelectorMouse();
	}

	void OnMouseUp(){
		MainMenu.instance.ButtonPressed(buttonName, gameObject,1);
	}

	public void SetSelected(bool isSelected){
		if(isSelected){
			this.renderer.material.color = Color.white;
		} else {
			this.renderer.material.color = Color.green;
		}
	}
	

}

